database-url: http://localhost:8086
export-url: http://localhost:4000
worker-type: 2
worker-count: 10
config:
  routing:
    - roadmap:
        url: "http://localhost"
        requestType: GET
        context: application/json
        statusCode: 200
  step-load:
    start: 1
    end: 10
    duration: 2min
    step: 1
server-config:
  host: localhost
  port: 6000
uuid: commit
platform: unix